name = "integration"
uuid = "a8c1efa4-32f4-4a26-a884-610be1cf5288"
authors = ["Mateusz Anikiej", "mateusz.anikiej@gmail.com"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
